/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // "../templates/**/*.{gohtml,html}",    // for locally generated templates
    "/templates/**/*.{gohtml,html}",     // for templates generated by docker-container
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

