version: "3.9"

services:
  db:
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 3333:8080
    environment:
      ADMINER_DESIGN: dracula
