-- Create or modify roles
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM pg_roles
    WHERE rolname = 'root'
) THEN CREATE ROLE root WITH SUPERUSER CREATEROLE CREATEDB REPLICATION BYPASSRLS;
ELSE ALTER ROLE root WITH SUPERUSER CREATEROLE CREATEDB REPLICATION BYPASSRLS;
END IF;
END $$;